#!/usr/bin/python

import sys
import re
from printer import Printer

def GetComment(line):
    what = re.compile(".*//(.*)").match(line)
    if what != None and len(what.groups()) > 0:
        return what.groups()[0]
    else:
        return ""

def ToCode(text):
    return text.decode("gbk").encode("utf8")


def Transform(filename, out):
    lines = open(filename).readlines()
    
    printer = Printer(out)
    printer.AppendLine("# -*- coding: utf8 -*-")
    printer.AppendLine("# Generated by inltoas.py. DO NOT EDIT!")

    re_assign = re.compile("MSGTYPE_DECLARE_ASSIGN\((\S+),\s*(\d+)\)")
    re_declare = re.compile("MSGTYPE_DECLARE\(\s*(\S+)\s*\)")
    
    index = 0
    for line in lines:
        if "MSGTYPE_BEGIN_BLOCK" in line:
            pass            
            
        
        # prase assign state
        what = re_assign.match(line)        
        if what != None:
            msgName = what.groups()[0]
            assIndex = what.groups()[1]

            comment = GetComment(line)   
                
            printer.AppendLine("%s = %s # %s"
                      % (msgName, assIndex, ToCode(comment)))
            index = int(assIndex)
            continue

        # parse declcare statements
        what = re_declare.match(line)
        if what != None:
            msgName=what.groups()[0]
            comment = GetComment(line)
            assIndex = index + 1
            printer.AppendLine("%s = %s; # %s"
                      % (msgName, assIndex, ToCode(comment)))
            index = assIndex
            continue
        
        line = line.strip()
        if line.startswith("//") or len(line) == 0:
            printer.AppendLine("# %s" % ToCode(line))
        else:
            printer.AppendLine("# %s" % ToCode(line))

    printer.Flush()


if __name__ == "__main__":
    """
    usage: inttopy.py INL_FILE OUT_FILE
    """
    input_path = sys.argv[1]
    output_path = None
    if len(sys.argv) > 2:
        output_path = sys.argv[2]
    Transform(input_path, output_path)
