#!/usr/bin/python

import sys
import re
from printer import Printer

def GetComment(line):
    what = re.compile(".*//(.*)").match(line)
    if what != None and len(what.groups()) > 0:
        comment = what.groups()[0]
        comment = comment.decode('gbk', 'ignore').encode('utf8')
        return comment
    else:
        return ""
        

def Transform(filename, out):
    lines = open(filename).readlines()
    
    printer = Printer(out)
    printer.AppendLine("// Generated by inltoas.py. DO NOT EDIT!")
    printer.AppendLine("package sixcube.protocol")
    printer.AppendLine("{")
    printer.IncIndent()
    printer.AppendLine("public final class MessageType")
    printer.AppendLine("{")
    printer.IncIndent()

    re_assign = re.compile("MSGTYPE_DECLARE_ASSIGN\((\S+),\s*(\d+)\)")
    re_declare = re.compile("MSGTYPE_DECLARE\(\s*(\S+)\s*\)")
    
    msgIdCheck = {}
    
    index = 0
    for line in lines:
        if "MSGTYPE_BEGIN_BLOCK" in line:
            pass            
            
        
        # prase assign state
        what = re_assign.match(line)        
        if what != None:
            msgName = what.groups()[0]
            assIndex = what.groups()[1]

            comment = GetComment(line)
            index = int(assIndex)
            
            if msgIdCheck.has_key(index):
                print "[ERROR]same msg id: \n\t[%s = %s]\n\t[%s = %s]" % (msgIdCheck[index], index,  msgName, index)
                sys.exit(-1)
            
            printer.AppendLine("public static var %s:int = %s; // %s"
                      % (msgName, assIndex, comment))
            msgIdCheck[index] = msgName
            continue

        # parse declcare statements
        what = re_declare.match(line)
        if what != None:
            msgName=what.groups()[0]
            comment = GetComment(line)
            assIndex = index + 1

            if msgIdCheck.has_key(assIndex):
                print "[ERROR]same msg id = %s: [%s][%s]\%s" % (assIndex, msgIdCheck[assIndex], msgName)
                sys.exit(-1)
            
            printer.AppendLine("public static const %s:int = %s; // %s"
                      % (msgName, assIndex, comment))
            msgIdCheck[assIndex] = msgName
            index = assIndex
            continue
        
        line = line.strip()
        line = line.decode('gbk', 'ignore').encode('utf8')
        if line.startswith("//") or len(line) == 0:
            printer.AppendLine("%s" % line)
        else:
            printer.AppendLine("// %s" % line)

    printer.DecIndent()
    printer.AppendLine("}")
    printer.DecIndent()
    printer.AppendLine("}")    
    printer.Flush()


if __name__ == "__main__":
    """
    usage: inttoas.py INL_FILE OUT_FILE
    """
    input_path = sys.argv[1]
    output_path = None
    if len(sys.argv) > 2:
        output_path = sys.argv[2]
    Transform(input_path, output_path)
